name: Build Sphinx projects and create PDF
on: [push, pull_request]
jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install pandoc
        run: |
          sudo apt-get install --no-install-recommends pandoc
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3"
      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Build Sphinx projects
        run: |
          ./build-sphinx.sh
      - uses: xu-cheng/latex-action@v2
        with:
          extra_system_packages: py3-pip
          # Sphinx is needed for pygmentize.py
          pre_compile: |
            python -m pip install sphinx
          root_file: Geier_Diss.tex
          latexmk_use_lualatex: true
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: Geier_Diss.pdf
